services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn sms_project.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_NAME: /data/db.sqlite3
    volumes:
      - sqlite_data:/data
      - media_data:/app/media

volumes:
  sqlite_data:
  media_data:
